# Distributed Arrays

In [1]:
using JuliaRunClient

In [4]:
initializeCluster(12)

INFO: waiting for 12...
INFO: workers started in 1.0016121864318848 seconds


Dict{String,Any} with 2 entries:
  "data" => JuliaRunClient for 12174009055273194445 @ http://juliarunremote-svc…
  "code" => 0

In [5]:
@everywhere using DistributedArrays

In [6]:
a=dzeros(12,12)

12×12 DistributedArrays.DArray{Float64,2,Array{Float64,2}}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [9]:
a=dfill(5.0, 12, 12)

12×12 DistributedArrays.DArray{Float64,2,Array{Float64,2}}:
 5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0

In [10]:
b=drand(1000,1000)

1000×1000 DistributedArrays.DArray{Float64,2,Array{Float64,2}}:
 0.403691   0.46897    0.457739   …  0.0349636  0.5117    0.919109  
 0.606375   0.713249   0.267151      0.975594   0.498865  0.679318  
 0.116209   0.484542   0.0740582     0.693086   0.380569  0.610809  
 0.957405   0.132701   0.796273      0.0982588  0.329043  0.587064  
 0.647431   0.387348   0.371503      0.964483   0.883691  0.290433  
 0.808158   0.0031073  0.0769654  …  0.529958   0.421581  0.194169  
 0.750994   0.0830387  0.586153      0.236443   0.60161   0.715128  
 0.48328    0.956374   0.267884      0.189519   0.584099  0.620797  
 0.26709    0.0332169  0.596844      0.116999   0.315768  0.858921  
 0.0991286  0.784457   0.473792      0.3841     0.828818  0.798312  
 0.870114   0.414957   0.352108   …  0.39121    0.588872  0.690426  
 0.753054   0.0592712  0.567508      0.699352   0.630008  0.609589  
 0.0954168  0.461987   0.69267       0.972445   0.919628  0.00938234
 ⋮                                ⋱    

In [21]:
procs(b)

4×3 Array{Int64,2}:
 2  6  10
 3  7  11
 4  8  12
 5  9  13

In [31]:
@time sum(b)

  0.002660 seconds (1.01 k allocations: 101.594 KiB)


500139.7311256226

In [12]:
convert(Array{Float64}, a)

12×12 Array{Float64,2}:
 5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0

In [24]:
?DArray

search: DArray @DArray SubDArray SubOrDArray SharedArray StridedArray DenseArray



```
DArray(init, dims, [procs, dist])
```

Construct a distributed array.

The parameter `init` is a function that accepts a tuple of index ranges. This function should allocate a local chunk of the distributed array and initialize it for the specified indices.

`dims` is the overall size of the distributed array.

`procs` optionally specifies a vector of process IDs to use. If unspecified, the array is distributed over all worker processes only. Typically, when running in distributed mode, i.e., nprocs() > 1, this would mean that no chunk of the distributed array exists on the process hosting the interactive julia prompt.

`dist` is an integer vector specifying how many chunks the distributed array should be divided into in each dimension.

For example, the `dfill` function that creates a distributed array and fills it with a value `v` is implemented as:

### Example

```jl
dfill(v, args...) = DArray(I->fill(v, map(length,I)), args...)
```


In [17]:
@everywhere function par(I)
    # create our local patch
    # I is a tuple of intervals, each interval is
    # regarded as a 1D array with integer entries
    # size(I[1], 1) gives the number of entries in I[1]
    # size(I[2], 1) gives the number of entries in I[2]
    d=(size(I[1], 1), size(I[2], 1))
    m = fill(myid(), d)
    return m
end

In [38]:
m = DArray(par, (800, 800))

800×800 DistributedArrays.DArray{Int64,2,Array{Int64,2}}:
 2  2  2  2  2  2  2  2  2  2  2  2  2  …  10  10  10  10  10  10  10  10  10
 2  2  2  2  2  2  2  2  2  2  2  2  2     10  10  10  10  10  10  10  10  10
 2  2  2  2  2  2  2  2  2  2  2  2  2     10  10  10  10  10  10  10  10  10
 2  2  2  2  2  2  2  2  2  2  2  2  2     10  10  10  10  10  10  10  10  10
 2  2  2  2  2  2  2  2  2  2  2  2  2     10  10  10  10  10  10  10  10  10
 2  2  2  2  2  2  2  2  2  2  2  2  2  …  10  10  10  10  10  10  10  10  10
 2  2  2  2  2  2  2  2  2  2  2  2  2     10  10  10  10  10  10  10  10  10
 2  2  2  2  2  2  2  2  2  2  2  2  2     10  10  10  10  10  10  10  10  10
 2  2  2  2  2  2  2  2  2  2  2  2  2     10  10  10  10  10  10  10  10  10
 2  2  2  2  2  2  2  2  2  2  2  2  2     10  10  10  10  10  10  10  10  10
 2  2  2  2  2  2  2  2  2  2  2  2  2  …  10  10  10  10  10  10  10  10  10
 2  2  2  2  2  2  2  2  2  2  2  2  2     10  10  10  10  10  10  10  10  10
 2  2 

In [33]:
m.indexes

4×3 Array{Tuple{UnitRange{Int64},UnitRange{Int64}},2}:
 (1:200, 1:267)    (1:200, 268:533)    (1:200, 534:800)  
 (201:400, 1:267)  (201:400, 268:533)  (201:400, 534:800)
 (401:600, 1:267)  (401:600, 268:533)  (401:600, 534:800)
 (601:800, 1:267)  (601:800, 268:533)  (601:800, 534:800)

In [37]:
rank(m)

LoadError: MethodError: no method matching svdvals!(::DistributedArrays.DArray{Float64,2,Array{Float64,2}})
Closest candidates are:
  svdvals!(::Union{Base.ReshapedArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2,A,MI} where MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{DenseArray, SubArray{T,N,P,I,true} where I<:Tuple{Union{Base.Slice, UnitRange},Vararg{Any,N} where N} where P where N where T}, DenseArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2}, SubArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2,A,I,L} where L} where I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex, Int64, Range{Int64}},N} where N} where A<:Union{Base.ReshapedArray{T,N,A,MI} where MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{DenseArray, SubArray{T,N,P,I,true} where I<:Tuple{Union{Base.Slice, UnitRange},Vararg{Any,N} where N} where P where N where T} where N where T, DenseArray}) where T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64} at linalg/svd.jl:130
  svdvals!(::Union{Base.ReshapedArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2,A,MI} where MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{DenseArray, SubArray{T,N,P,I,true} where I<:Tuple{Union{Base.Slice, UnitRange},Vararg{Any,N} where N} where P where N where T}, DenseArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2}, SubArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2,A,I,L} where L} where I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex, Int64, Range{Int64}},N} where N} where A<:Union{Base.ReshapedArray{T,N,A,MI} where MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{DenseArray, SubArray{T,N,P,I,true} where I<:Tuple{Union{Base.Slice, UnitRange},Vararg{Any,N} where N} where P where N where T} where N where T, DenseArray}, ::Union{Base.ReshapedArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2,A,MI} where MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{DenseArray, SubArray{T,N,P,I,true} where I<:Tuple{Union{Base.Slice, UnitRange},Vararg{Any,N} where N} where P where N where T}, DenseArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2}, SubArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2,A,I,L} where L} where I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex, Int64, Range{Int64}},N} where N} where A<:Union{Base.ReshapedArray{T,N,A,MI} where MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{DenseArray, SubArray{T,N,P,I,true} where I<:Tuple{Union{Base.Slice, UnitRange},Vararg{Any,N} where N} where P where N where T} where N where T, DenseArray}) where T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64} at linalg/svd.jl:289
  svdvals!(::Union{Hermitian{Complex{T},S}, Hermitian{T,S}, Symmetric{T,S}} where S where T<:Real) at linalg/symmetric.jl:456
  ...

In [35]:
mm = @spawnat 2 rank(localpart(m))
fetch(mm)

1

#### Credits
  * http://www.csd.uwo.ca/~moreno/cs2101a_moreno/Parallel_computing_with_Julia.pdf
  * 

In [ ]:
releaseCluster()